version: 1.0.{build}
skip_tags: true
image: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
cache:
- '%USERPROFILE%\.nuget\packages -> **\project.json'
- 'obj\tools -> tools\**'
before_build:
- ps: >-
    .\init.ps1

    & "${env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe" -Vr *,b03f5f7f11d50a3a
build:
  project: src\Microsoft.VisualStudio.Threading.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
