name: ðŸ“ƒ Docfx Validate

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main
    - microbuild

jobs:
  build:
    name: ðŸ“š Doc validation
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: ðŸ”— Markup Link Checker (mlc)
      uses: becheran/mlc@7ec24825cefe0c9c8c6bac48430e1f69e3ec356e # v1.2.0
      with:
        args: --do-not-warn-for-redirect-to https://learn.microsoft.com*,https://dotnet.microsoft.com/*,https://dev.azure.com/*,https://app.codecov.io/* -p docfx -i https://aka.ms/onboardsupport,https://aka.ms/spot,https://msrc.microsoft.com/*,https://www.microsoft.com/msrc*,https://microsoft.com/msrc*,https://www.npmjs.com/package/*,https://get.dot.net/
    - name: âš™ Install prerequisites
      run: |
        ./init.ps1 -UpgradePrerequisites
        dotnet --info
      shell: pwsh
    - name: ðŸ“š Verify docfx build
      run: dotnet docfx docfx/docfx.json --warningsAsErrors --disableGitFeatures
