steps:

- task: ms-vseng.MicroBuildTasks.965C8DC6-1483-45C9-B384-5AC75DA1F1A4.MicroBuildOptProfPlugin@2
  inputs:
    skipRunOptimize: true # set to false after we get some data
  displayName: Install OptProf Plugin

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
